version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: personal-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
    container_name: personal-frontend
    ports:
      - "3000:8080"  # Maps local 3000 to container's NGINX 8080
    environment:
      - NODE_ENV=development

